group=io.ballerina.lib
version=4.0.2-SNAPSHOT

spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=9.6.1
downloadPluginVersion=5.5.0
releasePluginVersion=3.1.0
ballerinaGradlePluginVersion=4.0.0

ballerinaLangVersion=2201.14.0-20260917-124200-7f273e6a
awsS3SdkVersion=2.42.0
stdlibAwsVersion=1.0.0
nettyVersion=4.2.18.Final
httpCoreVersion=4.4.16
httpClientVersion=4.5.13
eventStreamVersion=1.0.1
commonsLoggingVersion=1.2
commonsCodecVersion=1.17.1
reactiveStreamsVersion=1.0.4
slf4jVersion=1.7.36
awsCrtVersion=0.43.4
