[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "aws.s3"
version = "4.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid", "Vendor/Amazon"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.s3"

[build-options]
observabilityIncluded = true
